### PR TITLE
Add support for Electrumx

### PR DESCRIPTION
**Pull request by infertux**
AFAIK [Electrumx](https://github.com/kyuupichan/electrumx) is the only backend available for the Electron Cash wallet. I've been running a public bchd node for some time and figured I'd try to plug Electrumx to it.

This is a WIP - don't merge this PR for now. I'm opening it in order to document my findings:

1. `notls=1` must be set since Electrumx sends plaintext HTTP requests to the RPC server.

2. Electrumx makes use of batched requests, i.e. multiple RPC requests are sent at once in an array/vector. Thankfully, dcrd has already added support for it in [this commit](https://github.com/decred/dcrd/commit/a0438c81c3945bbe2a46846cea43d7115b2df89c). I was able to cherry-pick and (painfully) merge it into bchd.

3. Electrumx sends boolean parameters for the `getblock` command. However bchd only accepts a single integer verbosity level. I updated the API to accept two bools (inspired by dcrd). Note this is NOT backward compatible, I added more details in the commit message about it. [Bitcoin ABC accepts both integers and booleans](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/2f1adeefb67e985757cfae62b40c2edc5011b742/src/rpc/blockchain.cpp#L874-L881) but this feels messy and I'm not sure how to do it in Go.

With those changes, I was able to start Electrumx and it's currently syncing. I'll do further testing when it's done and report back.

```
INFO:LTORBlockProcessor:our height: 334,234 daemon: 590,246 UTXOs 972MB hist 251MB
[...]
INFO:DB:sync time: 39m 58s  ETA: 07h 33m 39s
```

Feedback welcome :)

### CODE REVIEW

**Comment by cpacia** [comment]
I think there's some interest in using electrum directly with bchd. There were some grpc changes that were requested to make that happen. I plan to work on that when I get some free time.

**Comment by infertux** [comment]
> I think there's some interest in using electrum directly with bchd

I assume you meant Electron Cash, not Electrum? Are the required gRPC changes documented somewhere?

---

As for my Electrumx instance, it has been running flawlessly for the last few days. It's most likely the only bchd powered Electrumx server out there :)

```
$ ./electrumx/electrumx_rpc getinfo
{
    "coin": "BitcoinCash",
    "daemon": "127.0.0.1:8334/",
    "daemon height": 590974,
    "db height": 590974,
[...]
    "request total": 92430,
 [...]
    "txs sent": 2,
    "uptime": "2d 22h 11m",
    "version": "ElectrumX 1.12"
}
```

Do you want bchd RPC API to be 100% compatible with Bitcoin ABC API? If so, I need to figure out how to make the `getblock` command accept both integers and booleans like ABC does. Otherwise, this PR is ready to be reviewed/merged.

**Comment by zquestz** [comment]
Overall this looks good, have you finished your testing and full sync?

**Comment by cpacia** [comment]
OK I've tested this with bchctl and bchwallet and everything seems to be working. Guess it looks good to merge.

**Pull request merged**
