### PR TITLE
Include small push data elements

### PR DESCRIPTION
**Pull request by jchavannes**

### CODE REVIEW

**Comment by cpacia** [comment]
Looks like this is only used when testing a script against a bloom filter, correct?

**Comment by jchavannes** [comment]
I actually don't see it used anywhere.  I am using BTCD as a library and ran into this issue.

**Comment by cpacia** [comment]
It's in the filter package. What I'm not understanding though is the need for it as someone looking to get a filter match can use a normal push data to get the same bytes onto the stack.

**Comment by jchavannes** [comment]
I'm not sure.  I am not using it for bloom filters.  `OP_0` was supported but `OP_1` through `OP_16` were missing so I added them.

**Comment by jchavannes** [comment]
I don't see this function used in bloom filters.  That said, these small push data work with bloom filters on normal BCH nodes.

**Comment by cpacia** [comment]
It's in the bloom package inside the bchutil package that is vendored. 

As far small push, I don't know if I see it in the C++ code https://github.com/Bitcoin-ABC/bitcoin-abc/blob/5e02f75dc9233dacbc073a7e8e78c240de8d7de9/src/bloom.cpp#L130

but maybe I could just be reading it wrong.

As I understand the script OP_1 through OP_16 push integers on the stack and bip37 requires the filter be tested against data elements (not integers).

**Comment by jchavannes** [comment]
Ahh, I see it now.  Good catch.  I will look into making a separate function, thanks.

**Comment by cpacia** [comment]
Np. Just submit a new PR with it.

**Pull request closed without merging**
