### PR TITLE
Add more proto documentation

### PR DESCRIPTION
**Pull request by 2qx**
Add more explanatory documentation to protoc methods, types and fields.

- Makes **no change** to the protocol itself. 
- Adds specificity for terms used to refer to many things, 
- Adds synonyms for words used interchangeably 
- Aims to provides an outside audience a succinct explanation,
  or enough key terms to obtain more information elsewhere.
- Note quirks and defaults, where possible.

### CODE REVIEW

**Comment by cpacia** [comment]
Thanks for the PR. Will take a look shortly.

**Comment by cpacia** [comment]
@2qx any chance you can update the method comments in bchrpc/server.go to match the new comments in the proto file?

**Comment by 2qx** [comment]
Will do.

**Comment by 2qx** [comment]
@cpacia, I matched the comments from the proto.  

In addition, there were some trailing whitespace in the protofile and some whitespace lines that I removed from the proto for consistency with go fmt.

**Pull request merged**
